version: "3"

services:
  heartbeatsMS:
    build: ./heartbeatsMS
    image: heartbeatsms:latest
    network_mode: host
  
  enforcementMS:
    build: ./enforcementMS
    image: enforcementms:latest
    network_mode: host

  fleetAPI:
    build: ./fleetAPI
    image: fleetapi:latest
    network_mode: host
    ports:
     - 3000
