version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "my-rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
     - RABBITMQ_DEFAULT_USER=rabbitmq
     - RABBITMQ_DEFAULT_PASS=rabbitmq
